[aids]
name = "AIDS"
desc = "Acquired Immune Deficiency Syndrome"

[aed]
name = "AED"
desc = "Automated External Defibrillator"

[atp]
name = "ATP"
desc = "Adenosine TriPhosphate"

[apc]
name = "APC"
desc = "Antigen-Presenting Cells"
