[ccu]
name = "CCU"
desc = "Coronary heart disease Care Unit"

[ct]
name = "CT"
desc = "Computed Tomography"

[cpr]
name = "CPR"
desc = "Cardiopulmonary Resuscitation"

[cdc]
name = "CDC"
desc = "Centers for Disease Control and Prevention"

[covid]
name = "COVID-19"
desc = "Coronavirus disease 2019"

[cthb]
name = "CTHB"
desc = "Total Concentration of hemoglobin"
