[ccu]
disp = "CCU"
desc = "Coronary heart disease Care Unit"

[ct]
disp = "CT"
desc = "Computed Tomography"

[cpr]
disp = "CPR"
desc = "Cardiopulmonary Resuscitation"

[cdc]
disp = "CDC"
desc = "Centers for Disease Control and Prevention"
