[hpv]
name = "HPV"
desc = "Human PapillomaVirus"
more = "A DNA virus"

[hb]
name = "Hb"
desc = "hemoglobin"

[hdl]
name = "HDL"
desc = "High-Density Lipoprotein"

[hla]
name = "HLA"
desc = "Human Leukocyte Antigen"

[hsv]
name = "HSV"
desc = "Herpes Simplex Virus"
